logging:
  level:
    ROOT: INFO

server:
  max-http-header-size: 32KB
  port: 8080
  ssl:
    enabled: false
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: Sleep-Logger-API
    timezone: UTC
  datasource:
    jdbc-url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/postgres
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    user: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/postgres
    driver-class-name: org.postgresql.Driver